/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OfficialsRouteImport } from './routes/officials'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LinksRouteImport } from './routes/links'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as ComplaintRouteImport } from './routes/complaint'
import { Route as ActivitiesRouteImport } from './routes/activities'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as AdminSubscriptionsRouteImport } from './routes/admin.subscriptions'
import { Route as AdminRecognitionRouteImport } from './routes/admin.recognition'
import { Route as AdminQuotesRouteImport } from './routes/admin.quotes'
import { Route as AdminMentorshipRouteImport } from './routes/admin.mentorship'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminMeetingsRouteImport } from './routes/admin.meetings'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminEventsRouteImport } from './routes/admin.events'
import { Route as AdminComplaintsRouteImport } from './routes/admin.complaints'
import { Route as AdminChapterRouteImport } from './routes/admin.chapter'
import { Route as AdminAlumniRouteImport } from './routes/admin.alumni'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OfficialsRoute = OfficialsRouteImport.update({
  id: '/officials',
  path: '/officials',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplaintRoute = ComplaintRouteImport.update({
  id: '/complaint',
  path: '/complaint',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesRoute = ActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ProfileRoute,
} as any)
const AdminSubscriptionsRoute = AdminSubscriptionsRouteImport.update({
  id: '/admin/subscriptions',
  path: '/admin/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRecognitionRoute = AdminRecognitionRouteImport.update({
  id: '/admin/recognition',
  path: '/admin/recognition',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminQuotesRoute = AdminQuotesRouteImport.update({
  id: '/admin/quotes',
  path: '/admin/quotes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMentorshipRoute = AdminMentorshipRouteImport.update({
  id: '/admin/mentorship',
  path: '/admin/mentorship',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/admin/members',
  path: '/admin/members',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMeetingsRoute = AdminMeetingsRouteImport.update({
  id: '/admin/meetings',
  path: '/admin/meetings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRoute = AdminEventsRouteImport.update({
  id: '/admin/events',
  path: '/admin/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminComplaintsRoute = AdminComplaintsRouteImport.update({
  id: '/admin/complaints',
  path: '/admin/complaints',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChapterRoute = AdminChapterRouteImport.update({
  id: '/admin/chapter',
  path: '/admin/chapter',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAlumniRoute = AdminAlumniRouteImport.update({
  id: '/admin/alumni',
  path: '/admin/alumni',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/complaint': typeof ComplaintRoute
  '/constitution': typeof ConstitutionRoute
  '/finance': typeof FinanceRoute
  '/gallery': typeof GalleryRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/officials': typeof OfficialsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/alumni': typeof AdminAlumniRoute
  '/admin/chapter': typeof AdminChapterRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/mentorship': typeof AdminMentorshipRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/recognition': typeof AdminRecognitionRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/complaint': typeof ComplaintRoute
  '/constitution': typeof ConstitutionRoute
  '/finance': typeof FinanceRoute
  '/gallery': typeof GalleryRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/officials': typeof OfficialsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/alumni': typeof AdminAlumniRoute
  '/admin/chapter': typeof AdminChapterRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/mentorship': typeof AdminMentorshipRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/recognition': typeof AdminRecognitionRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activities': typeof ActivitiesRoute
  '/complaint': typeof ComplaintRoute
  '/constitution': typeof ConstitutionRoute
  '/finance': typeof FinanceRoute
  '/gallery': typeof GalleryRoute
  '/links': typeof LinksRoute
  '/login': typeof LoginRoute
  '/members': typeof MembersRoute
  '/more': typeof MoreRoute
  '/notifications': typeof NotificationsRoute
  '/officials': typeof OfficialsRoute
  '/profile': typeof ProfileRouteWithChildren
  '/signup': typeof SignupRoute
  '/admin/alumni': typeof AdminAlumniRoute
  '/admin/chapter': typeof AdminChapterRoute
  '/admin/complaints': typeof AdminComplaintsRoute
  '/admin/events': typeof AdminEventsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/meetings': typeof AdminMeetingsRoute
  '/admin/members': typeof AdminMembersRoute
  '/admin/mentorship': typeof AdminMentorshipRoute
  '/admin/quotes': typeof AdminQuotesRoute
  '/admin/recognition': typeof AdminRecognitionRoute
  '/admin/subscriptions': typeof AdminSubscriptionsRoute
  '/profile/edit': typeof ProfileEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activities'
    | '/complaint'
    | '/constitution'
    | '/finance'
    | '/gallery'
    | '/links'
    | '/login'
    | '/members'
    | '/more'
    | '/notifications'
    | '/officials'
    | '/profile'
    | '/signup'
    | '/admin/alumni'
    | '/admin/chapter'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/meetings'
    | '/admin/members'
    | '/admin/mentorship'
    | '/admin/quotes'
    | '/admin/recognition'
    | '/admin/subscriptions'
    | '/profile/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activities'
    | '/complaint'
    | '/constitution'
    | '/finance'
    | '/gallery'
    | '/links'
    | '/login'
    | '/members'
    | '/more'
    | '/notifications'
    | '/officials'
    | '/profile'
    | '/signup'
    | '/admin/alumni'
    | '/admin/chapter'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/meetings'
    | '/admin/members'
    | '/admin/mentorship'
    | '/admin/quotes'
    | '/admin/recognition'
    | '/admin/subscriptions'
    | '/profile/edit'
  id:
    | '__root__'
    | '/'
    | '/activities'
    | '/complaint'
    | '/constitution'
    | '/finance'
    | '/gallery'
    | '/links'
    | '/login'
    | '/members'
    | '/more'
    | '/notifications'
    | '/officials'
    | '/profile'
    | '/signup'
    | '/admin/alumni'
    | '/admin/chapter'
    | '/admin/complaints'
    | '/admin/events'
    | '/admin/finance'
    | '/admin/meetings'
    | '/admin/members'
    | '/admin/mentorship'
    | '/admin/quotes'
    | '/admin/recognition'
    | '/admin/subscriptions'
    | '/profile/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivitiesRoute: typeof ActivitiesRoute
  ComplaintRoute: typeof ComplaintRoute
  ConstitutionRoute: typeof ConstitutionRoute
  FinanceRoute: typeof FinanceRoute
  GalleryRoute: typeof GalleryRoute
  LinksRoute: typeof LinksRoute
  LoginRoute: typeof LoginRoute
  MembersRoute: typeof MembersRoute
  MoreRoute: typeof MoreRoute
  NotificationsRoute: typeof NotificationsRoute
  OfficialsRoute: typeof OfficialsRoute
  ProfileRoute: typeof ProfileRouteWithChildren
  SignupRoute: typeof SignupRoute
  AdminAlumniRoute: typeof AdminAlumniRoute
  AdminChapterRoute: typeof AdminChapterRoute
  AdminComplaintsRoute: typeof AdminComplaintsRoute
  AdminEventsRoute: typeof AdminEventsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminMeetingsRoute: typeof AdminMeetingsRoute
  AdminMembersRoute: typeof AdminMembersRoute
  AdminMentorshipRoute: typeof AdminMentorshipRoute
  AdminQuotesRoute: typeof AdminQuotesRoute
  AdminRecognitionRoute: typeof AdminRecognitionRoute
  AdminSubscriptionsRoute: typeof AdminSubscriptionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/officials': {
      id: '/officials'
      path: '/officials'
      fullPath: '/officials'
      preLoaderRoute: typeof OfficialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/complaint': {
      id: '/complaint'
      path: '/complaint'
      fullPath: '/complaint'
      preLoaderRoute: typeof ComplaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities': {
      id: '/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof ActivitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof ProfileRoute
    }
    '/admin/subscriptions': {
      id: '/admin/subscriptions'
      path: '/admin/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AdminSubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/recognition': {
      id: '/admin/recognition'
      path: '/admin/recognition'
      fullPath: '/admin/recognition'
      preLoaderRoute: typeof AdminRecognitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/quotes': {
      id: '/admin/quotes'
      path: '/admin/quotes'
      fullPath: '/admin/quotes'
      preLoaderRoute: typeof AdminQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mentorship': {
      id: '/admin/mentorship'
      path: '/admin/mentorship'
      fullPath: '/admin/mentorship'
      preLoaderRoute: typeof AdminMentorshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/admin/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/meetings': {
      id: '/admin/meetings'
      path: '/admin/meetings'
      fullPath: '/admin/meetings'
      preLoaderRoute: typeof AdminMeetingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/admin/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/complaints': {
      id: '/admin/complaints'
      path: '/admin/complaints'
      fullPath: '/admin/complaints'
      preLoaderRoute: typeof AdminComplaintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/chapter': {
      id: '/admin/chapter'
      path: '/admin/chapter'
      fullPath: '/admin/chapter'
      preLoaderRoute: typeof AdminChapterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/alumni': {
      id: '/admin/alumni'
      path: '/admin/alumni'
      fullPath: '/admin/alumni'
      preLoaderRoute: typeof AdminAlumniRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProfileRouteChildren {
  ProfileEditRoute: typeof ProfileEditRoute
}

const ProfileRouteChildren: ProfileRouteChildren = {
  ProfileEditRoute: ProfileEditRoute,
}

const ProfileRouteWithChildren =
  ProfileRoute._addFileChildren(ProfileRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivitiesRoute: ActivitiesRoute,
  ComplaintRoute: ComplaintRoute,
  ConstitutionRoute: ConstitutionRoute,
  FinanceRoute: FinanceRoute,
  GalleryRoute: GalleryRoute,
  LinksRoute: LinksRoute,
  LoginRoute: LoginRoute,
  MembersRoute: MembersRoute,
  MoreRoute: MoreRoute,
  NotificationsRoute: NotificationsRoute,
  OfficialsRoute: OfficialsRoute,
  ProfileRoute: ProfileRouteWithChildren,
  SignupRoute: SignupRoute,
  AdminAlumniRoute: AdminAlumniRoute,
  AdminChapterRoute: AdminChapterRoute,
  AdminComplaintsRoute: AdminComplaintsRoute,
  AdminEventsRoute: AdminEventsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminMeetingsRoute: AdminMeetingsRoute,
  AdminMembersRoute: AdminMembersRoute,
  AdminMentorshipRoute: AdminMentorshipRoute,
  AdminQuotesRoute: AdminQuotesRoute,
  AdminRecognitionRoute: AdminRecognitionRoute,
  AdminSubscriptionsRoute: AdminSubscriptionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
